[build]
  publish = "dist"
  command = "npm run build"

[[headers]]
  for = "/assets/*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/assets/*.css"
  [headers.values]
    Content-Type = "text/css"

# SPA fallback - this should handle all routes that don't match files
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
